"""empty message

Revision ID: d6a1759ec94c
Revises: 
Create Date: 2019-09-28 18:45:01.027650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a1759ec94c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ratings', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
